pipeline:
  rtorrent:
    image: plugins/docker
    repo: 0xEmma/rtorrent
    tags: latest
    dockerfile: rtorrent.dockerfile
    secrets: [ docker_username, docker_password ]
  flood:
    image: plugins/docker
    repo: 0xEmma/flood
    tags: latest
    dockerfile: flood.dockerfile
    secrets: [ docker_username, docker_password ]
