version: '3'

services:
  rtorrent:
    build:
      context: .
      dockerfile: rtorrent.dockerfile
    volumes:
      - ./downloads:/data/downloads
      - sock:/data
    ports:
      - 6881:6881
      - 49264:49264
    tty: true
    logging:
      driver: none
  flood:
    build:
      context: .
      dockerfile: flood.dockerfile
    ports:
      - 3000:3000
    links:
      - rtorrent
    depends_on:
      - rtorrent
    environment:
      - RTORRENT_SOCK=true
      - NODE_ENV=development
    volumes:
      - ./downloads:/data/downloads
      - sock:/data

volumes:
  sock:
